# Set up your streams to rtsp here.
port: "558"
streams: # Cannot rename - must leave this as is.

  stream-ros:
    type: topic
    source: /image_topic
    mountpoint: /image_stream
    caps: video/x-raw,framerate=10/1,width=640,height=480
    bitrate: 500
